[package]
name = "sublime-shim"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "smerge"
path = "src/smerge.rs"

[[bin]]
name = "subl"
path = "src/subl.rs"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[dependencies]
